Project setup
andela/dashiki-healthchecks pull request #1
Opened 2017-06-14 16:36 UTC by SProjects

- Adds pre-commit git hook to enforce coding standards
- Adds Profile file and updates settings.py to enable Heroku deploy
- Adds configuration for Circle Ci and Travis CI
- Adds Travis, Coverall and Circle CI

2017-06-14 17:19 UTC, amwaleh requested changes

2017-06-14 17:19 UTC, amwaleh commented on .flake8
> +max-line-length=119
Aint this abit too long?

2017-06-14 17:19 UTC, amwaleh commented on hc/settings.py
> +if os.environ.get("ENVIRONMENT") == "staging":
Django used the environment variable **DEBUG** to check if we are in either Development or Production mode let use DEBUG.

2017-06-14 17:19 UTC, andela-amwaleh commented on hc/settings.py
> +if os.environ.get("ENVIRONMENT") == "production":
This might not be necessary

2017-06-14 17:24 UTC, andela-amwaleh commented
Rebase and Fixup the repeat commits, Then reword the commits to say what it will do 
e.g 
- [ **it will** ] `Update circle ci config`
- [ **it will** ] `Add badges for Travis, Coverall and Cicle CI`

2017-06-19 11:06 UTC, SProjects commented on .flake8
> +max-line-length=119
Discussed with TTL and left as is

2017-06-19 11:12 UTC, SProjects commented
- Updated settings.py to use DEBUG to differentiate environments.
- Removed and reworded commits to make commit history more consistent

2017-06-19 11:58 UTC, amwaleh approved these changes

2017-06-19 11:58 UTC, merged