[#147170299] Adjust timeout and grace period to exceed 30 days
andela/dashiki-healthchecks pull request #7
Opened 2017-06-27 13:18 UTC by charlieoduk

- Updated check.js to allow for timeout and grace period exceeding 30 days

- Removed CSS formatting from my_checks_desktop.html to display the modal headings on the left

2017-06-27 17:55 UTC, amwaleh requested changes
Niceeee !! work, please attend to the comments

2017-06-27 17:55 UTC, andela-amwaleh commented on static/js/checks.js
> +            values: [60, 3600, 86400, 2592000, (2592000 * 6), (2592000 * 12)],
please convert `2592000` into a constant to adhere to **DRY** principal

2017-06-27 17:55 UTC, andela-amwaleh commented on static/js/checks.js
> +            values: [60, 3600, 86400, 2592000, (2592000 * 6), (2592000 * 12)],
convert (2592000 * 6) and (2592000 * 12) into constants, this will enable changing of the value to be done in one place

2017-06-28 07:30 UTC, SProjects commented on static/js/checks.js
> +            values: [60, 3600, 86400, 2592000, (2592000 * 6), (2592000 * 12)],
The code has been DRYed.

2017-06-28 08:45 UTC, amwaleh submitted a review, later dismissed
Rebase the branch

2017-06-28 15:59 UTC, amwaleh submitted a review, later dismissed

2017-06-29 09:07 UTC, SProjects commented
@andela-amwaleh The conflict has been removed. I think the branch is ready to merge.

2017-07-05 14:27 UTC, amwaleh approved these changes

2017-07-05 17:14 UTC, merged